apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aJ5hD9ih,iv:4Fz8I1dXy8l1WJUiSfVM4Jqxtc/QqeWVIwuTYeM89Tg=,tag:P+DESQve/BBuM18J26NRAQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:WuHniG2Y6qz14Q==,iv:Xfu4+uSXq1KeW7mxOUSHDg5owKzKItPU8ebptv4zFzo=,tag:DeL8YTvhUTSQo9jt41KYBA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tyPZ3RgishOOGp6ZVK6dqX4=,iv:oA7jtmp0Wt2x+QqlXc4ffzp4c85enMK7p46l6GRD1GM=,tag:b3rlnAFs1q2Vs78J2UfPBw==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:40cwjfoQ/hXLKj/VeXzB/6NAzboCpy//Qymnsszc0HvkHLserYtz0Q==,iv:vk2GMpthJgVX4rjfuPnKOp9WqHJ0OGmOPycvandzYwE=,tag:PJyEjD5pZj6gEH9UGe0QzA==,type:str]
    SECRET_WEAVE_GITOPS_ADMIN_PASS_HASH: ENC[AES256_GCM,data:v5jSStb3gPxTSxJKGpPyusX3D92L6cd3zzNwnKLQsJzU4Ao7Y8Jd4ejvsTHT2vpS/lKBdiW5p8CS0/no,iv:905Un2lo0+hQ3EEw5Mri11ji0IMynDI1P2HU1404vLE=,tag:TNNjE0g1qqfO6aWzYCFjBA==,type:str]
    SECRET_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:aDd+uVE3nmxaHCDNp9ItrHnibhf6cW0NKecRyWB/b0wyP+q+akqJPkD7ZPBA2CL61ptaWQubBvb1VJxqsRuG6ewfTnKyci6wVHYfrieBvFlL7HJX4u7o79Fs+NvuACTrnNOaYIrn7+npQDyca8ZbYQdDyaVRiCMKkA==,iv:Fl1nuVtCygH5ySDzxzkww3jxLfyKVEoexuiyxzSRm7E=,tag:eOn3N5KMUnFBCzmDj5Q8Tg==,type:str]
    SECRET_GITHUB_TOKEN: ENC[AES256_GCM,data:l9yBGGB9cwIqbUqqzUcB3MAACgPab2iHJ4r8x5p8f2UZvD8UWy3zWyBpLNe0YKdkitkl5imIxKUaigxNfUDEgPTWz6VUpluxWZYz5VLFiBhnl8Cye4MgbfmnZh6u,iv:lkZHfagghNFxdAVuc7jHK713ufJNdtxTcJ7aNLbu5zE=,tag:7OuiVl9t/XebJPlz9vn3xg==,type:str]
    SECRET_GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:dQkxYyGNaBFtrGwTq00IsTlNTXzIf0yuBdl+7ZBNZ31K,iv:a0GWI1Brzle25v8LhOcbZrevNXIInM57+J/OVZBVIAI=,tag:poifeVF+iwdD4tE+1W/N0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qng9yfpg5kxrxvy0rjs2ve35w2t6vexz629ys4am4gtyjpflgzqxq2s0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZG56RU91a1c3UkM5TCt4
            bjlCVVRFTVdBclZhRHpJaFczRTdRdWV6N2cwCjZBMmdIYWNUV3o0Q2VVWEZSNE53
            cFkvNG5wZFpESVJ3Z25WWmpCQ3ZOODgKLS0tIDlKbzloUWhRNWVWUVBlaFRFUVQ5
            RkNteGxWcnFnczVzdXBvcSswYzVKVW8KXASMRBHXm3mlNPk8O9k2bJXKNF8TxQt8
            yMxVryjdcvbS0E4KusK8D021pG8b3pENUMcghcMR6XWW6cXvEF2Qzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T19:29:17Z"
    mac: ENC[AES256_GCM,data:diHSqebkxDadl5HjkXD0sH6pIdnNSUuMouJIGZP1DeCwSBeQ4AFZLSCq8RHSCZYmfcjxoGcTCoe6BItWAqoqGZ7rxgBq+ptjJGnOYyHMYy5p3ovGAG80j1376gUdLBQnQiJwFXY3qOWOp3bLVj9d3cgEaCaOklj69b/YAh/JSP8=,iv:H9h91P36hLHft7xV2gkWaTMvuhFFNPVzGGVrzJhF27Y=,tag:UHzu8Vxl4lPJtMEjNIfKQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
