---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  CLUSTER_NAME: "homelab-cluster"
  METALLB_LB_RANGE: "10.0.6.101-10.0.6.255"
  METALLB_K8S_GATEWAY_ADDR: "10.0.6.101"
  METALLB_INGRESS_ADDR: "10.0.6.102"
  KUBE_VIP_ADDR: "10.0.6.100"
